# Generated by Django 5.2 on 2025-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_roll_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
