# Generated by Django 5.0.7 on 2024-07-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolmember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='poolmember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='poolmember',
            name='phone_number',
        ),
    ]
