# Generated by Django 5.0.7 on 2025-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pool', '0002_remove_poolmember_gender_remove_poolmember_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='is_female_only',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PoolRequest',
        ),
    ]
